packages:
  - apps/*
  - packages/*

overrides:
  '@hono/node-server': '>=1.19.10'
  '@prisma/generator-helper@4.16.2>cross-spawn': 7.0.6
  hono: '>=4.11.4'
  nodemailer: '>=8.0.2'
  valibot: '>=1.2.0'

shellEmulator: true

publicHoistPattern:
  - '@types/react'
  - '@types/react-dom'

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  bufferutil: true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
