version: '3.7'

services:
  postgres:
    container_name: amber-postgres
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "54320:5432"
    stop_signal: SIGINT
    environment:
      - POSTGRES_USER=ggp
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: -c log_statement=all -c log_min_error_statement=error
    volumes:
      - amber-postgres-data:/var/lib/postgresql/data
#  mysql:
#    container_name: acnw-mysql
#    image: mysql:5.7
#    restart: unless-stopped
#    ports:
#      - "33060:3306"
#    stop_signal: SIGINT
#    environment:
#      - MYSQL_ROOT_PASSWORD=rootPassword
#      - MYSQL_ROOT_HOST='%'

volumes:
  amber-postgres-data:
