import { describe, expect, test } from 'vitest'

import { buildSpecialGameCreationPlan } from './special'

describe('special game planning helper', () => {
  test('creates only missing special games using the latest slot-specific and any-game templates', () => {
    const plan = buildSpecialGameCreationPlan({
      slots: [{ id: 1 }, { id: 2 }, { id: 3 }],
      existingSpecialGames: [
        { slotId: 1, category: 'no_game' },
        { slotId: null, category: 'any_game' },
      ],
      noGameTemplates: [
        {
          slotId: 2,
          description: 'Latest slot 2',
          lateFinish: false,
          lateStart: null,
          name: 'No Game 2',
          playerMax: 10,
          playerMin: 0,
          roomId: null,
          shortName: null,
          charInstructions: '',
          estimatedLength: '2h',
          gameContactEmail: '',
          genre: 'other',
          gmNames: null,
          message: '',
          playerPreference: 'Any',
          playersContactGm: false,
          returningPlayers: '',
          setting: '',
          slotConflicts: '',
          slotPreference: 0,
          teenFriendly: true,
          type: 'Other',
          authorId: null,
          full: false,
        },
        {
          slotId: 2,
          description: 'Older slot 2',
          lateFinish: true,
          lateStart: 'late',
          name: 'Outdated',
          playerMax: 5,
          playerMin: 1,
          roomId: 12,
          shortName: 'old',
          charInstructions: 'old',
          estimatedLength: '1h',
          gameContactEmail: 'old@example.com',
          genre: 'mystery',
          gmNames: 'Old GM',
          message: 'old',
          playerPreference: 'Fixed',
          playersContactGm: true,
          returningPlayers: 'old',
          setting: 'old',
          slotConflicts: 'old',
          slotPreference: 9,
          teenFriendly: false,
          type: 'Larp',
          authorId: 99,
          full: true,
        },
      ],
      anyGameTemplate: {
        description: 'Existing any game template',
        lateFinish: false,
        lateStart: null,
        name: 'Any Game',
        playerMax: 999,
        playerMin: 0,
        roomId: null,
        shortName: null,
        charInstructions: '',
        estimatedLength: 'n/a',
        gameContactEmail: '',
        genre: 'other',
        gmNames: null,
        message: '',
        playerPreference: 'Any',
        playersContactGm: false,
        returningPlayers: '',
        setting: '',
        slotConflicts: '',
        slotPreference: 0,
        teenFriendly: true,
        type: 'Other',
        authorId: null,
        full: false,
      },
      year: 2026,
    })

    expect(plan.noGameCreates).toEqual([
      {
        slotId: 2,
        year: 2026,
        category: 'no_game',
        description: 'Latest slot 2',
        lateFinish: false,
        lateStart: null,
        name: 'No Game 2',
        playerMax: 10,
        playerMin: 0,
        roomId: null,
        shortName: null,
        charInstructions: '',
        estimatedLength: '2h',
        gameContactEmail: '',
        genre: 'other',
        gmNames: null,
        message: '',
        playerPreference: 'Any',
        playersContactGm: false,
        returningPlayers: '',
        setting: '',
        slotConflicts: '',
        slotPreference: 0,
        teenFriendly: true,
        type: 'Other',
        authorId: null,
        full: false,
      },
      {
        slotId: 3,
        year: 2026,
        category: 'no_game',
        description: 'I am taking this slot off.',
        lateFinish: false,
        lateStart: null,
        name: 'No Game',
        playerMax: 999,
        playerMin: 0,
        roomId: null,
        shortName: null,
        charInstructions: '',
        estimatedLength: 'n/a',
        gameContactEmail: '',
        genre: 'other',
        gmNames: null,
        message: '',
        playerPreference: 'Any',
        playersContactGm: false,
        returningPlayers: '',
        setting: '',
        slotConflicts: '',
        slotPreference: 0,
        teenFriendly: true,
        type: 'Other',
        authorId: null,
        full: false,
      },
    ])
    expect(plan.anyGameCreate).toBeNull()
  })

  test('falls back to default templates when no special games exist yet', () => {
    const plan = buildSpecialGameCreationPlan({
      slots: [{ id: 7 }],
      existingSpecialGames: [],
      noGameTemplates: [],
      anyGameTemplate: null,
      year: 2027,
    })

    expect(plan.noGameCreates).toEqual([
      expect.objectContaining({
        slotId: 7,
        year: 2027,
        category: 'no_game',
        name: 'No Game',
        description: 'I am taking this slot off.',
      }),
    ])
    expect(plan.anyGameCreate).toEqual(
      expect.objectContaining({
        slotId: null,
        year: 2027,
        category: 'any_game',
        name: 'Any Game',
        description: 'Assign me to any game in this slot.',
      }),
    )
  })
})
