import { dbAdmin as prisma } from '../../src/db'

const assertTestDatabase = () => {
  const url = process.env.DATABASE_URL ?? ''
  const allowedTestDatabases: Array<string> = ['acnw_test', 'acus_test']
  const isAllowed = allowedTestDatabases.some((databaseName) => url.includes(databaseName))
  if (!isAllowed) {
    throw new Error(
      `Refusing to seed non-test database. Expected DATABASE_URL to contain one of '${allowedTestDatabases.join(', ')}', got '${url}'.`,
    )
  }
}

const settingsData = [
  { id: 1, code: 'config.abbr', type: 'string', value: 'acnw' },
  { id: 2, code: 'config.baseTimeZone', type: 'string', value: 'America/Los_Angeles' },
  { id: 3, code: 'config.contactEmail', type: 'string', value: 'acnw@wyrdrune.com' },
  { id: 4, code: 'config.conventionEndDate', type: 'date', value: '2025-11-09T00:00:00.000-08:00' },
  { id: 5, code: 'config.conventionStartDate', type: 'date', value: '2025-11-06T00:00:00.000-08:00' },
  { id: 6, code: 'config.copyright', type: 'string', value: 'amberconnw.org' },
  { id: 7, code: 'config.deposit', type: 'number', value: '50' },
  { id: 8, code: 'config.firstDataYear', type: 'number', value: '2012' },
  { id: 9, code: 'config.fourDayMembership', type: 'number', value: '240' },
  { id: 10, code: 'config.fourDayVoucher', type: 'number', value: '70' },
  { id: 11, code: 'config.gameBookOpen', type: 'date', value: '2025-09-08T00:00:00.000-07:00' },
  { id: 12, code: 'config.gameChoicesDue', type: 'date', value: '2025-09-15T00:00:00.000-07:00' },
  { id: 13, code: 'config.gameEmail', type: 'string', value: 'game@wyrdrune.com' },
  { id: 14, code: 'config.gameGmFeedbackDeadline', type: 'date', value: '2025-08-18T00:00:00.000-07:00' },
  { id: 15, code: 'config.gameGmPreview', type: 'date', value: '2025-08-25T00:00:00.000-07:00' },
  { id: 16, code: 'config.gameRoomCredit', type: 'string', value: '$160' },
  { id: 17, code: 'config.gameSubmissionDeadline', type: 'date', value: '2025-08-11T00:00:00.000-07:00' },
  { id: 18, code: 'config.gmPreview', type: 'date', value: '2025-09-18T00:00:00.000-07:00' },
  { id: 19, code: 'config.hotelBookingCode', type: 'string', value: '-' },
  { id: 20, code: 'config.hotelBookingLastdate', type: 'date', value: '2025-06-01T00:00:00.000-07:00' },
  { id: 21, code: 'config.hotelBookingUrl', type: 'string', value: '-' },
  { id: 22, code: 'config.lastCancellationFullRefund', type: 'date', value: '2025-10-17T00:00:00.000-07:00' },
  { id: 23, code: 'config.maxPlayersCeiling', type: 'number', value: '150' },
  { id: 24, code: 'config.maxPlayersFloor', type: 'number', value: '1' },
  { id: 25, code: 'config.minPlayersCeiling', type: 'number', value: '10' },
  { id: 26, code: 'config.minPlayersFloor', type: 'number', value: '1' },
  { id: 27, code: 'config.mondayBeforeCon', type: 'date', value: '2025-11-03T00:00:00.000-08:00' },
  { id: 28, code: 'config.moreThanDoubleOccupancySurcharge', type: 'string', value: '$15' },
  { id: 29, code: 'config.name', type: 'string', value: 'ACNW' },
  { id: 30, code: 'config.numberOfSlots', type: 'number', value: '7' },
  { id: 31, code: 'config.oregonHotelTax', type: 'string', value: '13.95%' },
  { id: 32, code: 'config.paymentDeadline', type: 'date', value: '2025-08-11T00:00:00.000-07:00' },
  { id: 33, code: 'config.playerMax', type: 'number', value: '10' },
  { id: 34, code: 'config.playerMin', type: 'number', value: '4' },
  { id: 35, code: 'config.registrationDeadline', type: 'date', value: '2025-08-26T00:00:00.000-07:00' },
  { id: 36, code: 'config.registrationOpen', type: 'date', value: '2025-06-14T23:57:06.000-07:00' },
  { id: 37, code: 'config.schedulesSent', type: 'date', value: '2025-09-22T00:00:00.000-07:00' },
  { id: 38, code: 'config.startDates.2012.date', type: 'date', value: '2012-11-08T00:00:00.000-08:00' },
  { id: 39, code: 'config.startDates.2012.slots', type: 'number', value: '7' },
  { id: 40, code: 'config.startDates.2012.virtual', type: 'boolean', value: 'false' },
  { id: 41, code: 'config.startDates.2013.date', type: 'date', value: '2013-11-07T00:00:00.000-08:00' },
  { id: 42, code: 'config.startDates.2013.slots', type: 'number', value: '7' },
  { id: 43, code: 'config.startDates.2013.virtual', type: 'boolean', value: 'false' },
  { id: 44, code: 'config.startDates.2014.date', type: 'date', value: '2014-11-06T00:00:00.000-08:00' },
  { id: 45, code: 'config.startDates.2014.slots', type: 'number', value: '7' },
  { id: 46, code: 'config.startDates.2014.virtual', type: 'boolean', value: 'false' },
  { id: 47, code: 'config.startDates.2015.date', type: 'date', value: '2015-11-12T00:00:00.000-08:00' },
  { id: 48, code: 'config.startDates.2015.slots', type: 'number', value: '7' },
  { id: 49, code: 'config.startDates.2015.virtual', type: 'boolean', value: 'false' },
  { id: 50, code: 'config.startDates.2016.date', type: 'date', value: '2016-11-03T00:00:00.000-07:00' },
  { id: 51, code: 'config.startDates.2016.slots', type: 'number', value: '7' },
  { id: 52, code: 'config.startDates.2016.virtual', type: 'boolean', value: 'false' },
  { id: 53, code: 'config.startDates.2017.date', type: 'date', value: '2017-11-02T00:00:00.000-07:00' },
  { id: 54, code: 'config.startDates.2017.slots', type: 'number', value: '7' },
  { id: 55, code: 'config.startDates.2017.virtual', type: 'boolean', value: 'false' },
  { id: 56, code: 'config.startDates.2018.date', type: 'date', value: '2018-11-01T00:00:00.000-07:00' },
  { id: 57, code: 'config.startDates.2018.slots', type: 'number', value: '7' },
  { id: 58, code: 'config.startDates.2018.virtual', type: 'boolean', value: 'false' },
  { id: 59, code: 'config.startDates.2019.date', type: 'date', value: '2019-10-31T00:00:00.000-07:00' },
  { id: 60, code: 'config.startDates.2019.slots', type: 'number', value: '7' },
  { id: 61, code: 'config.startDates.2019.virtual', type: 'boolean', value: 'false' },
  { id: 62, code: 'config.startDates.2020.date', type: 'date', value: '2020-11-05T00:00:00.000-08:00' },
  { id: 63, code: 'config.startDates.2020.slots', type: 'number', value: '7' },
  { id: 64, code: 'config.startDates.2020.virtual', type: 'boolean', value: 'true' },
  { id: 65, code: 'config.startDates.2021.date', type: 'date', value: '2021-11-04T00:00:00.000-07:00' },
  { id: 66, code: 'config.startDates.2021.slots', type: 'number', value: '7' },
  { id: 67, code: 'config.startDates.2021.virtual', type: 'boolean', value: 'true' },
  { id: 68, code: 'config.startDates.2022.date', type: 'date', value: '2022-11-03T00:00:00.000-07:00' },
  { id: 69, code: 'config.startDates.2022.slots', type: 'number', value: '7' },
  { id: 70, code: 'config.startDates.2022.virtual', type: 'boolean', value: 'false' },
  { id: 71, code: 'config.startDates.2023.date', type: 'date', value: '2023-11-02T00:00:00.000-07:00' },
  { id: 72, code: 'config.startDates.2023.slots', type: 'number', value: '7' },
  { id: 73, code: 'config.startDates.2023.virtual', type: 'boolean', value: 'false' },
  { id: 74, code: 'config.startDates.2024.date', type: 'date', value: '2024-11-07T00:00:00.000-08:00' },
  { id: 75, code: 'config.startDates.2024.slots', type: 'number', value: '7' },
  { id: 76, code: 'config.startDates.2024.virtual', type: 'boolean', value: 'false' },
  { id: 77, code: 'config.startDates.2025.date', type: 'date', value: '2025-11-06T00:00:00.000-08:00' },
  { id: 78, code: 'config.startDates.2025.slots', type: 'number', value: '7' },
  { id: 79, code: 'config.startDates.2025.virtual', type: 'boolean', value: 'false' },
  { id: 80, code: 'config.startYear', type: 'number', value: '1997' },
  { id: 81, code: 'config.subsidizedMembership', type: 'number', value: '170' },
  { id: 82, code: 'config.subsidizedMembershipShort', type: 'number', value: '130' },
  { id: 83, code: 'config.threeDayMembership', type: 'number', value: '180' },
  { id: 84, code: 'config.threeDayVoucher', type: 'number', value: '50' },
  { id: 85, code: 'config.title', type: 'string', value: 'Ambercon NW' },
  { id: 86, code: 'config.travelCoordination', type: 'date', value: '2025-10-17T00:00:00.000-07:00' },
  { id: 87, code: 'config.useUsAttendanceOptions', type: 'boolean', value: 'false' },
  { id: 88, code: 'config.virtual', type: 'boolean', value: 'false' },
  { id: 89, code: 'config.virtualCost', type: 'string', value: '' },
  { id: 90, code: 'config.webEmail', type: 'string', value: 'guy@wyrdrune.com' },
  { id: 91, code: 'config.wednesdayAfterCon', type: 'date', value: '2025-11-12T00:00:00.000-08:00' },
  { id: 92, code: 'config.year', type: 'number', value: '2025' },
  { id: 93, code: 'flag.allow_game_signup', type: 'perm-gate', value: 'Member' },
  { id: 94, code: 'flag.allow_payment', type: 'perm-gate', value: 'Yes' },
  { id: 95, code: 'flag.allow_registration', type: 'perm-gate', value: 'Yes' },
  { id: 96, code: 'flag.dev_use_detail_room_quantities', type: 'perm-gate', value: 'No' },
  { id: 97, code: 'flag.display_gamebook', type: 'perm-gate', value: 'Yes' },
  { id: 98, code: 'flag.display_schedule', type: 'perm-gate', value: 'Member' },
  { id: 99, code: 'flag.display_virtual_details', type: 'perm-gate', value: 'No' },
  { id: 100, code: 'flag.is_beta', type: 'perm-gate', value: 'No' },
  { id: 101, code: 'flag.send_admin_email', type: 'perm-gate', value: 'No' },
  { id: 102, code: 'url.discord', type: 'string', value: 'https://discord.gg/jcFSNhW' },
  { id: 103, code: 'url.wiki', type: 'string', value: 'http://amberconnw.wikidot.com/' },
  { id: 104, code: 'flag.allow_game_submission', type: 'perm-gate', value: 'Yes' },
  { id: 105, code: 'flag.allow_game_editing', type: 'perm-gate', value: 'Yes' },
]

const lookups = [
  { id: 1, realm: 'interest', internationalize: false, ordering: 'sequencer', codeType: 'string', valueType: 'string' },
  {
    id: 2,
    realm: 'attendance',
    internationalize: false,
    ordering: 'sequencer',
    codeType: 'string',
    valueType: 'string',
  },
  { id: 3, realm: 'roomType', internationalize: false, ordering: 'sequencer', codeType: 'string', valueType: 'string' },
  { id: 4, realm: 'roomPref', internationalize: false, ordering: 'sequencer', codeType: 'string', valueType: 'string' },
  {
    id: 5,
    realm: 'gamePlayerPref',
    internationalize: false,
    ordering: 'sequencer',
    codeType: 'string',
    valueType: 'string',
  },
  {
    id: 6,
    realm: 'bathroomType',
    internationalize: false,
    ordering: 'sequencer',
    codeType: 'string',
    valueType: 'string',
  },
]

const lookupValues = [
  {
    id: 1,
    lookupId: 1,
    code: 'Full',
    numericSequencer: 0,
    sequencer: 1,
    stringSequencer: '_',
    value: 'I am sending payment in full now',
  },
  {
    id: 2,
    lookupId: 1,
    code: 'Deposit',
    numericSequencer: 0,
    sequencer: 2,
    stringSequencer: '_',
    value: 'I am paying a deposit of $50 now. I understand payment in full is due August 5, 2019.',
  },
  {
    id: 3,
    lookupId: 2,
    code: 'Thurs-Sun',
    numericSequencer: 0,
    sequencer: 1,
    stringSequencer: '_',
    value: 'Full: $185.',
  },
  {
    id: 4,
    lookupId: 2,
    code: 'Fri-Sun',
    numericSequencer: 0,
    sequencer: 2,
    stringSequencer: '_',
    value: 'Short: $135.',
  },
  { id: 5, lookupId: 3, code: 'twin', numericSequencer: 0, sequencer: 1, stringSequencer: '_', value: 'Twin' },
  { id: 6, lookupId: 3, code: 'queen', numericSequencer: 0, sequencer: 2, stringSequencer: '_', value: 'Queen' },
  { id: 7, lookupId: 3, code: 'king', numericSequencer: 0, sequencer: 3, stringSequencer: '_', value: 'King' },
  {
    id: 8,
    lookupId: 3,
    code: 'double queen',
    numericSequencer: 0,
    sequencer: 4,
    stringSequencer: '_',
    value: 'Double Queen',
  },
  { id: 9, lookupId: 3, code: 'hostel', numericSequencer: 0, sequencer: 5, stringSequencer: '_', value: 'Hostel' },
  { id: 10, lookupId: 3, code: 'family', numericSequencer: 0, sequencer: 6, stringSequencer: '_', value: 'Family' },
  { id: 11, lookupId: 3, code: 'other', numericSequencer: 0, sequencer: 7, stringSequencer: '_', value: 'other' },
  {
    id: 12,
    lookupId: 4,
    code: 'room-with',
    numericSequencer: 0,
    sequencer: 1,
    stringSequencer: '_',
    value: 'I will be rooming with (list names)',
  },
  {
    id: 13,
    lookupId: 4,
    code: 'assign-me',
    numericSequencer: 0,
    sequencer: 2,
    stringSequencer: '_',
    value: "I don't mind who I room with; please assign me a roommate. (Double Queen option only.)",
  },
  { id: 14, lookupId: 4, code: 'other', numericSequencer: 0, sequencer: 3, stringSequencer: '_', value: 'None' },
  {
    id: 15,
    lookupId: 5,
    code: 'ret-only',
    numericSequencer: 0,
    sequencer: 1,
    stringSequencer: '_',
    value: 'Returning players only',
  },
  {
    id: 16,
    lookupId: 5,
    code: 'ret-pref',
    numericSequencer: 0,
    sequencer: 2,
    stringSequencer: '_',
    value: 'Returning players have preference, new players welcome.',
  },
  { id: 17, lookupId: 5, code: 'any', numericSequencer: 0, sequencer: 3, stringSequencer: '_', value: 'Any' },
  { id: 18, lookupId: 6, code: 'en-suite', numericSequencer: 0, sequencer: 1, stringSequencer: '_', value: 'en-suite' },
  {
    id: 19,
    lookupId: 6,
    code: 'no en-suite',
    numericSequencer: 0,
    sequencer: 2,
    stringSequencer: '_',
    value: 'no en-suite',
  },
  { id: 20, lookupId: 6, code: 'other', numericSequencer: 0, sequencer: 3, stringSequencer: '_', value: 'other' },
]

const slots = [
  { id: 1, slot: 1, day: 'Thursday', formattedDate: 'October 31, 2019', length: '5 hrs', time: '7 pm to midnight' },
  { id: 2, slot: 2, day: 'Friday', formattedDate: 'November 1, 2019', length: '4 hrs', time: '9 am to 1 pm' },
  { id: 3, slot: 3, day: 'Friday', formattedDate: 'November 1, 2019', length: '4.5 hrs', time: '2 pm to 6:30 pm' },
  { id: 4, slot: 4, day: 'Friday', formattedDate: 'November 1, 2019', length: '4 hrs', time: '8 pm to midnight' },
  { id: 5, slot: 5, day: 'Saturday', formattedDate: 'November 2, 2019', length: '7.5 hrs', time: '9 am to 4:30 pm' },
  { id: 6, slot: 6, day: 'Saturday', formattedDate: 'November 2, 2019', length: '5 hrs', time: '7 pm to midnight' },
  { id: 7, slot: 7, day: 'Sunday', formattedDate: 'November 3, 2019', length: '6.5 hrs', time: '10 am to 4:30 pm' },
]

const rooms = [
  { id: 1, description: 'Cascade Ballroom', size: 16, type: 'tabletop', updated: false },
  { id: 2, description: 'Summit Room', size: 10, type: 'tabletop', updated: false },
  { id: 3, description: 'Studio A', size: 8, type: 'tabletop', updated: false },
]

const hotelRoomDetails = [
  {
    id: 1n,
    version: 1n,
    bathroomType: 'en-suite',
    comment: 'Double Queen standard',
    enabled: true,
    gamingRoom: false,
    internalRoomType: 'double queen',
    name: 'Cascade Double Queen',
    reserved: false,
    reservedFor: '',
    roomType: 'double queen',
    formattedRoomType: 'Double Queen',
  },
  {
    id: 2n,
    version: 1n,
    bathroomType: 'en-suite',
    comment: 'Queen standard',
    enabled: true,
    gamingRoom: false,
    internalRoomType: 'queen',
    name: 'Summit Queen',
    reserved: false,
    reservedFor: '',
    roomType: 'queen',
    formattedRoomType: 'Queen',
  },
  {
    id: 3n,
    version: 1n,
    bathroomType: 'en-suite',
    comment: 'Hostel style space used as gaming overflow',
    enabled: true,
    gamingRoom: true,
    internalRoomType: 'hostel',
    name: 'Evergreen Hostel',
    reserved: false,
    reservedFor: '',
    roomType: 'hostel',
    formattedRoomType: 'Hostel',
  },
]

const hotelRooms = [
  {
    id: 1,
    description: 'Cascade Double Queen',
    gamingRoom: false,
    occupancy: '2',
    quantity: 4,
    rate: '$220',
    bathroomType: 'en-suite',
    type: 'double queen',
  },
  {
    id: 2,
    description: 'Summit Queen',
    gamingRoom: false,
    occupancy: '2',
    quantity: 4,
    rate: '$200',
    bathroomType: 'en-suite',
    type: 'queen',
  },
  {
    id: 3,
    description: 'Evergreen Hostel',
    gamingRoom: true,
    occupancy: '6',
    quantity: 1,
    rate: '$0',
    bathroomType: 'en-suite',
    type: 'hostel',
  },
]

const roles = [
  { id: 1, authority: 'ROLE_USER' },
  { id: 2, authority: 'ROLE_ADMIN' },
  { id: 3, authority: 'ROLE_GAME_ADMIN' },
  { id: 4, authority: 'ROLE_ADMIN_FILTER' },
  { id: 5, authority: 'ROLE_REPORTS' },
]

const users = [
  {
    id: 1,
    email: 'alex.admin@example.com',
    firstName: 'Alex',
    lastName: 'Admin',
    displayName: 'Alex A',
    fullName: 'Alex Admin',
  },
  {
    id: 2,
    email: 'casey.coordinator@example.com',
    firstName: 'Casey',
    lastName: 'Coordinator',
    displayName: 'Casey C',
    fullName: 'Casey Coordinator',
  },
  {
    id: 3,
    email: 'bailey.builder@example.com',
    firstName: 'Bailey',
    lastName: 'Builder',
    displayName: 'Bailey B',
    fullName: 'Bailey Builder',
  },
  {
    id: 4,
    email: 'drew.doe@example.com',
    firstName: 'Drew',
    lastName: 'Doe',
    displayName: 'Drew D',
    fullName: 'Drew Doe',
  },
  {
    id: 5,
    email: 'elliot.evergreen@example.com',
    firstName: 'Elliot',
    lastName: 'Evergreen',
    displayName: 'Elliot E',
    fullName: 'Elliot Evergreen',
  },
  {
    id: 6,
    email: 'frankie.fable@example.com',
    firstName: 'Frankie',
    lastName: 'Fable',
    displayName: 'Frankie F',
    fullName: 'Frankie Fable',
  },
  {
    id: 7,
    email: 'harper.haven@example.com',
    firstName: 'Harper',
    lastName: 'Haven',
    displayName: 'Harper H',
    fullName: 'Harper Haven',
  },
  {
    id: 8,
    email: 'indigo.ivy@example.com',
    firstName: 'Indigo',
    lastName: 'Ivy',
    displayName: 'Indigo I',
    fullName: 'Indigo Ivy',
  },
  {
    id: 9,
    email: 'jordan.jade@example.com',
    firstName: 'Jordan',
    lastName: 'Jade',
    displayName: 'Jordan J',
    fullName: 'Jordan Jade',
  },
  {
    id: 10,
    email: 'kiran.kestrel@example.com',
    firstName: 'Kiran',
    lastName: 'Kestrel',
    displayName: 'Kiran K',
    fullName: 'Kiran Kestrel',
  },
]

// Note that the there's an insertion trigger that ensures that every user gets the ROLE_USER (1)
const userRoles = [
  { roleId: 2, userId: 1 },
  { roleId: 2, userId: 2 },
]

const memberships = [
  {
    id: 1,
    userId: 1,
    year: 2024,
    arrivalDate: new Date('2024-11-06T18:00:00.000-08:00'),
    departureDate: new Date('2024-11-10T17:00:00.000-08:00'),
    attendance: 'Thurs-Sun',
    attending: true,
    hotelRoomId: 1,
    interestLevel: 'Full',
    message: 'Ready for the full weekend.',
    roomPreferenceAndNotes: 'Quiet floor if possible.',
    roomingPreferences: 'room-with',
    roomingWith: 'Casey Coordinator',
    volunteer: true,
    offerSubsidy: false,
    requestOldPrice: false,
    slotsAttending: '1,2,3,4,5,6,7',
    cost: 240,
  },
  {
    id: 2,
    userId: 2,
    year: 2024,
    arrivalDate: new Date('2024-11-06T20:00:00.000-08:00'),
    departureDate: new Date('2024-11-10T16:00:00.000-08:00'),
    attendance: 'Thurs-Sun',
    attending: true,
    hotelRoomId: 1,
    interestLevel: 'Full',
    message: 'Staff volunteer.',
    roomPreferenceAndNotes: 'Near reg desk.',
    roomingPreferences: 'assign-me',
    roomingWith: '',
    volunteer: true,
    offerSubsidy: false,
    requestOldPrice: false,
    slotsAttending: '1,2,3,4,5,6,7',
    cost: 240,
  },
  {
    id: 3,
    userId: 3,
    year: 2024,
    arrivalDate: new Date('2024-11-07T08:30:00.000-08:00'),
    departureDate: new Date('2024-11-10T15:30:00.000-08:00'),
    attendance: 'Fri-Sun',
    attending: true,
    hotelRoomId: 2,
    interestLevel: 'Deposit',
    message: 'First time attending.',
    roomPreferenceAndNotes: 'Happy to share.',
    roomingPreferences: 'assign-me',
    roomingWith: '',
    volunteer: false,
    offerSubsidy: false,
    requestOldPrice: false,
    slotsAttending: '2,3,4,5,6,7',
    cost: 180,
  },
  {
    id: 4,
    userId: 4,
    year: 2024,
    arrivalDate: new Date('2024-11-07T12:00:00.000-08:00'),
    departureDate: new Date('2024-11-10T13:00:00.000-08:00'),
    attendance: 'Fri-Sun',
    attending: true,
    hotelRoomId: 2,
    interestLevel: 'Full',
    message: 'Prefers shorter games.',
    roomPreferenceAndNotes: 'Close to elevator.',
    roomingPreferences: 'other',
    roomingWith: 'Quiet roommate',
    volunteer: false,
    offerSubsidy: true,
    requestOldPrice: false,
    slotsAttending: '2,3,4,5,6',
    cost: 180,
  },
  {
    id: 5,
    userId: 5,
    year: 2024,
    arrivalDate: new Date('2024-11-07T09:00:00.000-08:00'),
    departureDate: new Date('2024-11-10T12:00:00.000-08:00'),
    attendance: 'Thurs-Sun',
    attending: true,
    hotelRoomId: 3,
    interestLevel: 'Full',
    message: 'GMing one slot.',
    roomPreferenceAndNotes: 'In the hostel to be near gaming.',
    roomingPreferences: 'assign-me',
    roomingWith: 'Hostel bunk',
    volunteer: true,
    offerSubsidy: false,
    requestOldPrice: false,
    slotsAttending: '1,2,3,4,5,6,7',
    cost: 0,
  },
  {
    id: 6,
    userId: 6,
    year: 2024,
    arrivalDate: new Date('2024-11-07T10:00:00.000-08:00'),
    departureDate: new Date('2024-11-09T18:00:00.000-08:00'),
    attendance: 'Fri-Sun',
    attending: false,
    hotelRoomId: 2,
    interestLevel: 'Deposit',
    message: 'Might attend virtually if enabled.',
    roomPreferenceAndNotes: 'No strong preference.',
    roomingPreferences: 'assign-me',
    roomingWith: '',
    volunteer: false,
    offerSubsidy: false,
    requestOldPrice: false,
    slotsAttending: '2,3,4',
    cost: 0,
  },
  {
    id: 7,
    userId: 7,
    year: 2025,
    arrivalDate: new Date('2025-11-05T19:00:00.000-08:00'),
    departureDate: new Date('2025-11-09T16:00:00.000-08:00'),
    attendance: 'Thurs-Sun',
    attending: true,
    hotelRoomId: 1,
    interestLevel: 'Full',
    message: 'Returning player from last year.',
    roomPreferenceAndNotes: 'Prefers quiet wing.',
    roomingPreferences: 'room-with',
    roomingWith: 'Jordan Jade',
    volunteer: false,
    offerSubsidy: false,
    requestOldPrice: false,
    slotsAttending: '1,2,3,4,5,6,7',
    cost: 240,
  },
  {
    id: 8,
    userId: 8,
    year: 2025,
    arrivalDate: new Date('2025-11-06T09:00:00.000-08:00'),
    departureDate: new Date('2025-11-09T12:00:00.000-08:00'),
    attendance: 'Fri-Sun',
    attending: true,
    hotelRoomId: 2,
    interestLevel: 'Full',
    message: 'Interested in horror and mystery.',
    roomPreferenceAndNotes: 'Likes early mornings.',
    roomingPreferences: 'assign-me',
    roomingWith: '',
    volunteer: false,
    offerSubsidy: false,
    requestOldPrice: false,
    slotsAttending: '2,3,4,5,6,7',
    cost: 180,
  },
  {
    id: 9,
    userId: 9,
    year: 2025,
    arrivalDate: new Date('2025-11-06T11:30:00.000-08:00'),
    departureDate: new Date('2025-11-09T11:30:00.000-08:00'),
    attendance: 'Fri-Sun',
    attending: true,
    hotelRoomId: 1,
    interestLevel: 'Deposit',
    message: 'Needs accessibility in room assignments.',
    roomPreferenceAndNotes: 'Near elevator and low floor.',
    roomingPreferences: 'other',
    roomingWith: 'Accessibility preferred',
    volunteer: false,
    offerSubsidy: true,
    requestOldPrice: false,
    slotsAttending: '2,3,4,5,6,7',
    cost: 170,
  },
  {
    id: 10,
    userId: 10,
    year: 2025,
    arrivalDate: new Date('2025-11-06T14:00:00.000-08:00'),
    departureDate: new Date('2025-11-09T14:30:00.000-08:00'),
    attendance: 'Thurs-Sun',
    attending: true,
    hotelRoomId: 3,
    interestLevel: 'Full',
    message: 'GMing two slots.',
    roomPreferenceAndNotes: 'Fine with hostel bunks.',
    roomingPreferences: 'assign-me',
    roomingWith: 'Hostel bunk',
    volunteer: true,
    offerSubsidy: false,
    requestOldPrice: false,
    slotsAttending: '1,2,3,4,5,6,7',
    cost: 0,
  },
  {
    id: 11,
    userId: 3,
    year: 2025,
    arrivalDate: new Date('2025-11-06T08:30:00.000-08:00'),
    departureDate: new Date('2025-11-09T15:30:00.000-08:00'),
    attendance: 'Fri-Sun',
    attending: true,
    hotelRoomId: 2,
    interestLevel: 'Deposit',
    message: 'Second year attendee, loves pulp.',
    roomPreferenceAndNotes: 'Shared room is fine.',
    roomingPreferences: 'assign-me',
    roomingWith: '',
    volunteer: false,
    offerSubsidy: false,
    requestOldPrice: false,
    slotsAttending: '2,3,4,5,6,7',
    cost: 180,
  },
  {
    id: 12,
    userId: 4,
    year: 2025,
    arrivalDate: new Date('2025-11-06T12:00:00.000-08:00'),
    departureDate: new Date('2025-11-08T20:00:00.000-08:00'),
    attendance: 'Fri-Sun',
    attending: true,
    hotelRoomId: 2,
    interestLevel: 'Full',
    message: 'Prefers short games and social space.',
    roomPreferenceAndNotes: 'Close to lobby.',
    roomingPreferences: 'other',
    roomingWith: 'Friend in same block',
    volunteer: false,
    offerSubsidy: false,
    requestOldPrice: false,
    slotsAttending: '2,3,4,5',
    cost: 180,
  },
]

const games = [
  {
    id: 1,
    name: 'Shadows Over Rebma',
    shortName: 'Rebma',
    description: 'Political intrigue beneath the waves of Rebma with shifting alliances.',
    message: 'Expect courtly scheming and occasional duels.',
    charInstructions: 'Pre-gens provided; bring d10s.',
    estimatedLength: '5h',
    gameContactEmail: 'alex.admin@example.com',
    genre: 'Fantasy',
    gmNames: 'Alex Admin',
    playerPreference: 'ret-only',
    playersContactGm: true,
    returningPlayers: 'Returning arc from 2023',
    setting: 'Amber',
    slotConflicts: '',
    slotPreference: 1,
    teenFriendly: true,
    type: 'Tabletop',
    year: 2024,
    playerMax: 6,
    playerMin: 4,
    roomId: 1,
    slotId: 1,
    authorId: 1,
    lateFinish: false,
    lateStart: null,
    full: false,
  },
  {
    id: 2,
    name: 'Patternfall Skirmish',
    shortName: 'Patternfall',
    description: 'Tactical romp through shadow combat and war councils.',
    message: 'Rules-light tactical decisions with character drama.',
    charInstructions: 'Bring two favorite conflicts your PC wants to resolve.',
    estimatedLength: '4h',
    gameContactEmail: 'casey.coordinator@example.com',
    genre: 'Adventure',
    gmNames: 'Casey Coordinator',
    playerPreference: 'ret-pref',
    playersContactGm: false,
    returningPlayers: 'New players welcome',
    setting: 'Shadow War',
    slotConflicts: '',
    slotPreference: 2,
    teenFriendly: true,
    type: 'Tabletop',
    year: 2024,
    playerMax: 8,
    playerMin: 4,
    roomId: 2,
    slotId: 2,
    authorId: 2,
    lateFinish: false,
    lateStart: null,
    full: false,
  },
  {
    id: 3,
    name: 'Courts of Chaos Masquerade',
    shortName: 'Masquerade',
    description: 'Social LARP in the Courts with hidden agendas and masks.',
    message: 'Roleplay-forward, light mechanics.',
    charInstructions: 'Costumes encouraged; light physical activity.',
    estimatedLength: '4h',
    gameContactEmail: 'elliot.evergreen@example.com',
    genre: 'Mystery',
    gmNames: 'Elliot Evergreen',
    playerPreference: 'any',
    playersContactGm: false,
    returningPlayers: 'Standalone story',
    setting: 'Courts of Chaos',
    slotConflicts: 'Avoids slot 5',
    slotPreference: 3,
    teenFriendly: false,
    type: 'LARP',
    year: 2024,
    playerMax: 12,
    playerMin: 6,
    roomId: 1,
    slotId: 3,
    authorId: 5,
    lateFinish: false,
    lateStart: 'Starts 15 minutes late for setup',
    full: false,
  },
  {
    id: 4,
    name: 'Road to Tir-na Nog',
    shortName: 'Tir-na Nog',
    description: 'Quest through shifting shadows to reach a mythical city.',
    message: 'Exploration heavy; puzzles and negotiation.',
    charInstructions: 'Pregens provided.',
    estimatedLength: '4h',
    gameContactEmail: 'frankie.fable@example.com',
    genre: 'Fantasy',
    gmNames: 'Frankie Fable',
    playerPreference: 'ret-pref',
    playersContactGm: false,
    returningPlayers: 'Ideal for newcomers',
    setting: 'Shadow Road',
    slotConflicts: '',
    slotPreference: 4,
    teenFriendly: true,
    type: 'Tabletop',
    year: 2024,
    playerMax: 7,
    playerMin: 4,
    roomId: 2,
    slotId: 4,
    authorId: 6,
    lateFinish: false,
    lateStart: null,
    full: false,
  },
  {
    id: 5,
    name: 'Revelations at Kolvir',
    shortName: 'Kolvir',
    description: 'High-level strategy session for princes of Amber.',
    message: 'Debate heavy; light dice.',
    charInstructions: 'Bring one agenda item your PC must achieve.',
    estimatedLength: '7h',
    gameContactEmail: 'alex.admin@example.com',
    genre: 'Drama',
    gmNames: 'Alex Admin',
    playerPreference: 'ret-only',
    playersContactGm: true,
    returningPlayers: 'Follow-up to Shadows Over Rebma',
    setting: 'Kolvir',
    slotConflicts: 'Avoids slot 3 crew overlap',
    slotPreference: 5,
    teenFriendly: false,
    type: 'Tabletop',
    year: 2024,
    playerMax: 6,
    playerMin: 4,
    roomId: 1,
    slotId: 5,
    authorId: 1,
    lateFinish: false,
    lateStart: null,
    full: false,
  },
  {
    id: 6,
    name: 'Late Night in the Pattern Room',
    shortName: 'Pattern Room',
    description: 'Small, intense scenario exploring the Pattern itself.',
    message: 'Character-driven; may end late.',
    charInstructions: 'Pregens provided.',
    estimatedLength: '5h',
    gameContactEmail: 'casey.coordinator@example.com',
    genre: 'Horror',
    gmNames: 'Casey Coordinator',
    playerPreference: 'any',
    playersContactGm: false,
    returningPlayers: 'Works standalone',
    setting: 'Pattern',
    slotConflicts: '',
    slotPreference: 6,
    teenFriendly: false,
    type: 'Tabletop',
    year: 2024,
    playerMax: 5,
    playerMin: 3,
    roomId: 3,
    slotId: 6,
    authorId: 2,
    lateFinish: true,
    lateStart: null,
    full: false,
  },
  {
    id: 7,
    name: 'Sunday Wind-Down: Tea and Tales',
    shortName: 'Tea & Tales',
    description: 'Low-key storytelling to close the con.',
    message: 'Great for anyone without an assignment.',
    charInstructions: 'No prep needed.',
    estimatedLength: '4h',
    gameContactEmail: 'elliot.evergreen@example.com',
    genre: 'Slice',
    gmNames: 'Elliot Evergreen',
    playerPreference: 'any',
    playersContactGm: false,
    returningPlayers: 'All welcome',
    setting: 'Random Shadows',
    slotConflicts: '',
    slotPreference: 7,
    teenFriendly: true,
    type: 'Tabletop',
    year: 2024,
    playerMax: 12,
    playerMin: 4,
    roomId: 3,
    slotId: 7,
    authorId: 5,
    lateFinish: false,
    lateStart: null,
    full: false,
  },
  {
    id: 8,
    name: 'Siege of the Argent Keep',
    shortName: 'Argent Keep',
    description: 'Defend a key shadow against invading armies.',
    message: 'Mix of tactics and diplomacy.',
    charInstructions: 'Bring a defensive tactic your PC favors.',
    estimatedLength: '5h',
    gameContactEmail: 'kiran.kestrel@example.com',
    genre: 'Adventure',
    gmNames: 'Kiran Kestrel',
    playerPreference: 'ret-pref',
    playersContactGm: false,
    returningPlayers: 'New arc',
    setting: 'Shadow Keep',
    slotConflicts: '',
    slotPreference: 1,
    teenFriendly: true,
    type: 'Tabletop',
    year: 2025,
    playerMax: 8,
    playerMin: 4,
    roomId: 1,
    slotId: 1,
    authorId: 10,
    lateFinish: false,
    lateStart: null,
    full: false,
  },
  {
    id: 9,
    name: 'Ghosts of Tir-na Nog',
    shortName: 'Ghosts',
    description: 'Sequel trek with haunting callbacks.',
    message: 'Callbacks to Road to Tir-na Nog but new-player friendly.',
    charInstructions: 'Pregens updated; bring curiosity.',
    estimatedLength: '4h',
    gameContactEmail: 'frankie.fable@example.com',
    genre: 'Fantasy',
    gmNames: 'Frankie Fable',
    playerPreference: 'any',
    playersContactGm: false,
    returningPlayers: 'Returning arc',
    setting: 'Shadow Road',
    slotConflicts: '',
    slotPreference: 2,
    teenFriendly: true,
    type: 'Tabletop',
    year: 2025,
    playerMax: 7,
    playerMin: 4,
    roomId: 2,
    slotId: 2,
    authorId: 6,
    lateFinish: false,
    lateStart: null,
    full: false,
  },
  {
    id: 10,
    name: 'Chaos Carnival',
    shortName: 'Carnival',
    description: 'LARP of traveling performers with secrets.',
    message: 'Light-touch mechanics, big emotions.',
    charInstructions: 'Costumes welcome; keep movement light.',
    estimatedLength: '4h',
    gameContactEmail: 'indigo.ivy@example.com',
    genre: 'Mystery',
    gmNames: 'Indigo Ivy',
    playerPreference: 'any',
    playersContactGm: false,
    returningPlayers: 'Standalone',
    setting: 'Courts of Chaos',
    slotConflicts: '',
    slotPreference: 3,
    teenFriendly: false,
    type: 'LARP',
    year: 2025,
    playerMax: 14,
    playerMin: 8,
    roomId: 1,
    slotId: 3,
    authorId: 8,
    lateFinish: false,
    lateStart: 'Setup requires 15 minutes',
    full: false,
  },
  {
    id: 11,
    name: 'Patternfall Debrief',
    shortName: 'Debrief',
    description: 'Table talk and fallout from the Siege.',
    message: 'Story-focused, minimal mechanics.',
    charInstructions: 'Bring aftermath goals.',
    estimatedLength: '4h',
    gameContactEmail: 'casey.coordinator@example.com',
    genre: 'Drama',
    gmNames: 'Casey Coordinator',
    playerPreference: 'ret-only',
    playersContactGm: true,
    returningPlayers: 'Follow-up for Siege PCs',
    setting: 'Patternfall',
    slotConflicts: '',
    slotPreference: 4,
    teenFriendly: false,
    type: 'Tabletop',
    year: 2025,
    playerMax: 6,
    playerMin: 4,
    roomId: 2,
    slotId: 4,
    authorId: 2,
    lateFinish: false,
    lateStart: null,
    full: false,
  },
  {
    id: 12,
    name: 'Night Watch in Amber',
    shortName: 'Night Watch',
    description: 'Late night guard duty with supernatural incidents.',
    message: 'Small table, late finish likely.',
    charInstructions: 'Pregens with secrets provided.',
    estimatedLength: '5h',
    gameContactEmail: 'harper.haven@example.com',
    genre: 'Horror',
    gmNames: 'Harper Haven',
    playerPreference: 'any',
    playersContactGm: false,
    returningPlayers: 'New story',
    setting: 'Amber City',
    slotConflicts: '',
    slotPreference: 6,
    teenFriendly: false,
    type: 'Tabletop',
    year: 2025,
    playerMax: 5,
    playerMin: 3,
    roomId: 3,
    slotId: 6,
    authorId: 7,
    lateFinish: true,
    lateStart: null,
    full: false,
  },
  {
    id: 13,
    name: 'Sunday Epilogues',
    shortName: 'Epilogues',
    description: 'Casual storytelling circle to close arcs.',
    message: 'Open table; flexible seating.',
    charInstructions: 'Bring your favorite moment from the weekend.',
    estimatedLength: '4h',
    gameContactEmail: 'kiran.kestrel@example.com',
    genre: 'Slice',
    gmNames: 'Kiran Kestrel',
    playerPreference: 'any',
    playersContactGm: false,
    returningPlayers: 'Everyone welcome',
    setting: 'Various Shadows',
    slotConflicts: '',
    slotPreference: 7,
    teenFriendly: true,
    type: 'Tabletop',
    year: 2025,
    playerMax: 14,
    playerMin: 6,
    roomId: 3,
    slotId: 7,
    authorId: 10,
    lateFinish: false,
    lateStart: null,
    full: false,
  },
  {
    id: 14,
    name: 'Crossroads of Sable',
    shortName: 'Sable',
    description: 'Negotiations at a shadow crossroads where alliances shift.',
    message: 'Emphasis on social play.',
    charInstructions: 'Bring a secret your character guards.',
    estimatedLength: '4h',
    gameContactEmail: 'jordan.jade@example.com',
    genre: 'Intrigue',
    gmNames: 'Jordan Jade',
    playerPreference: 'any',
    playersContactGm: false,
    returningPlayers: 'Standalone',
    setting: 'Sable Crossroads',
    slotConflicts: '',
    slotPreference: 5,
    teenFriendly: true,
    type: 'Tabletop',
    year: 2025,
    playerMax: 6,
    playerMin: 3,
    roomId: 2,
    slotId: 5,
    authorId: 9,
    lateFinish: false,
    lateStart: null,
    full: false,
  },
  {
    id: 15,
    name: 'Midnight Signals',
    shortName: 'Signals',
    description: 'Investigate a shadow broadcast cutting through the Pattern.',
    message: 'Mystery with optional puzzles.',
    charInstructions: 'Bring a question your PC wants answered.',
    estimatedLength: '5h',
    gameContactEmail: 'bailey.builder@example.com',
    genre: 'Mystery',
    gmNames: 'Bailey Builder',
    playerPreference: 'any',
    playersContactGm: false,
    returningPlayers: 'New story',
    setting: 'Signal Station',
    slotConflicts: '',
    slotPreference: 6,
    teenFriendly: true,
    type: 'Tabletop',
    year: 2025,
    playerMax: 7,
    playerMin: 4,
    roomId: 1,
    slotId: 6,
    authorId: 3,
    lateFinish: false,
    lateStart: null,
    full: false,
  },
]

const gameChoices = [
  { id: 1, gameId: 1, memberId: 1, rank: 1, slotId: 1, year: 2024, returningPlayer: true },
  { id: 2, gameId: 2, memberId: 1, rank: 2, slotId: 2, year: 2024, returningPlayer: true },
  { id: 3, gameId: 5, memberId: 1, rank: 3, slotId: 5, year: 2024, returningPlayer: true },
  { id: 4, gameId: 2, memberId: 2, rank: 1, slotId: 2, year: 2024, returningPlayer: false },
  { id: 5, gameId: 4, memberId: 2, rank: 2, slotId: 4, year: 2024, returningPlayer: false },
  { id: 6, gameId: 6, memberId: 2, rank: 3, slotId: 6, year: 2024, returningPlayer: false },
  { id: 7, gameId: 3, memberId: 3, rank: 1, slotId: 3, year: 2024, returningPlayer: false },
  { id: 8, gameId: 2, memberId: 3, rank: 2, slotId: 2, year: 2024, returningPlayer: false },
  { id: 9, gameId: 6, memberId: 3, rank: 3, slotId: 6, year: 2024, returningPlayer: false },
  { id: 10, gameId: 4, memberId: 4, rank: 1, slotId: 4, year: 2024, returningPlayer: false },
  { id: 11, gameId: 6, memberId: 4, rank: 2, slotId: 6, year: 2024, returningPlayer: false },
  { id: 12, gameId: 3, memberId: 4, rank: 3, slotId: 3, year: 2024, returningPlayer: false },
  { id: 13, gameId: 3, memberId: 5, rank: 1, slotId: 3, year: 2024, returningPlayer: true },
  { id: 14, gameId: 7, memberId: 5, rank: 2, slotId: 7, year: 2024, returningPlayer: true },
  { id: 15, gameId: 5, memberId: 5, rank: 3, slotId: 5, year: 2024, returningPlayer: true },
  { id: 16, gameId: 6, memberId: 6, rank: 1, slotId: 6, year: 2024, returningPlayer: false },
  { id: 17, gameId: 4, memberId: 6, rank: 2, slotId: 4, year: 2024, returningPlayer: false },
  { id: 18, gameId: 2, memberId: 6, rank: 3, slotId: 2, year: 2024, returningPlayer: false },
  { id: 19, gameId: 8, memberId: 7, rank: 1, slotId: 1, year: 2025, returningPlayer: false },
  { id: 20, gameId: 9, memberId: 7, rank: 2, slotId: 2, year: 2025, returningPlayer: false },
  { id: 21, gameId: 11, memberId: 7, rank: 3, slotId: 4, year: 2025, returningPlayer: false },
  { id: 22, gameId: 9, memberId: 8, rank: 1, slotId: 2, year: 2025, returningPlayer: false },
  { id: 23, gameId: 10, memberId: 8, rank: 2, slotId: 3, year: 2025, returningPlayer: false },
  { id: 24, gameId: 12, memberId: 8, rank: 3, slotId: 6, year: 2025, returningPlayer: false },
  { id: 25, gameId: 8, memberId: 9, rank: 1, slotId: 1, year: 2025, returningPlayer: false },
  { id: 26, gameId: 10, memberId: 9, rank: 2, slotId: 3, year: 2025, returningPlayer: false },
  { id: 27, gameId: 12, memberId: 9, rank: 3, slotId: 6, year: 2025, returningPlayer: false },
  { id: 28, gameId: 8, memberId: 10, rank: 1, slotId: 1, year: 2025, returningPlayer: true },
  { id: 29, gameId: 10, memberId: 10, rank: 2, slotId: 3, year: 2025, returningPlayer: true },
  { id: 30, gameId: 13, memberId: 10, rank: 3, slotId: 7, year: 2025, returningPlayer: true },
  { id: 31, gameId: 9, memberId: 11, rank: 1, slotId: 2, year: 2025, returningPlayer: true },
  { id: 32, gameId: 11, memberId: 11, rank: 2, slotId: 4, year: 2025, returningPlayer: true },
  { id: 33, gameId: 13, memberId: 11, rank: 3, slotId: 7, year: 2025, returningPlayer: true },
  { id: 34, gameId: 10, memberId: 12, rank: 1, slotId: 3, year: 2025, returningPlayer: false },
  { id: 35, gameId: 11, memberId: 12, rank: 2, slotId: 4, year: 2025, returningPlayer: false },
  { id: 36, gameId: 12, memberId: 12, rank: 3, slotId: 6, year: 2025, returningPlayer: false },
  { id: 37, gameId: 12, memberId: 10, rank: 0, slotId: 6, year: 2025, returningPlayer: true },
]

const gameAssignments = [
  { memberId: 1, gameId: 1, gm: 0, year: 2024 },
  { memberId: 2, gameId: 2, gm: 0, year: 2024 },
  { memberId: 3, gameId: 3, gm: 0, year: 2024 },
  { memberId: 4, gameId: 4, gm: 0, year: 2024 },
  { memberId: 5, gameId: 3, gm: 1, year: 2024 },
  { memberId: 1, gameId: 5, gm: 1, year: 2024 },
  { memberId: 2, gameId: 6, gm: 1, year: 2024 },
  { memberId: 7, gameId: 8, gm: 0, year: 2025 },
  { memberId: 8, gameId: 9, gm: 0, year: 2025 },
  { memberId: 9, gameId: 10, gm: 0, year: 2025 },
  { memberId: 10, gameId: 8, gm: 1, year: 2025 },
  { memberId: 10, gameId: 13, gm: 1, year: 2025 },
  { memberId: 11, gameId: 11, gm: 0, year: 2025 },
  { memberId: 12, gameId: 10, gm: 0, year: 2025 },
  { memberId: 7, gameId: 12, gm: 1, year: 2025 },
  { memberId: 8, gameId: 12, gm: 0, year: 2025 },
  { memberId: 9, gameId: 12, gm: 0, year: 2025 },
  { memberId: 10, gameId: 12, gm: 0, year: 2025 },
  { memberId: 11, gameId: 12, gm: 0, year: 2025 },
  { memberId: 12, gameId: 12, gm: 0, year: 2025 },
]

const gameSubmissions = [
  {
    id: 1,
    memberId: 8,
    year: 2025,
    message: 'Please avoid late-night horror; early slots preferred.',
  },
  {
    id: 2,
    memberId: 10,
    year: 2025,
    message: 'Happy to GM but prefer smaller tables.',
  },
]

const resetTables = async () => {
  await prisma.gameAssignment.deleteMany()
  await prisma.gameChoice.deleteMany()
  await prisma.game.deleteMany()
  await prisma.gameSubmission.deleteMany()
  await prisma.shirtOrderItem.deleteMany()
  await prisma.shirtOrder.deleteMany()
  await prisma.transactions.deleteMany()
  await prisma.stripe.deleteMany()
  await prisma.membership.deleteMany()
  await prisma.userRole.deleteMany()
  await prisma.role.deleteMany()
  await prisma.profile.deleteMany()
  await prisma.user.deleteMany()
  await prisma.hotelRoom.deleteMany()
  await prisma.hotelRoomDetails.deleteMany()
  await prisma.room.deleteMany()
  await prisma.slot.deleteMany()
  await prisma.lookupValue.deleteMany()
  await prisma.lookup.deleteMany()
  await prisma.setting.deleteMany()
}

const resetMembershipSequence = async () => {
  await prisma.$executeRawUnsafe(
    "SELECT setval(pg_get_serial_sequence('membership', 'id'), (SELECT COALESCE(MAX(id), 1) FROM membership), true)",
  )
}

export const seed = async () => {
  assertTestDatabase()
  try {
    await resetTables()

    await prisma.setting.createMany({ data: settingsData })
    await prisma.lookup.createMany({ data: lookups })
    await prisma.lookupValue.createMany({ data: lookupValues })
    await prisma.slot.createMany({ data: slots })
    await prisma.room.createMany({ data: rooms })
    await prisma.hotelRoomDetails.createMany({ data: hotelRoomDetails })
    await prisma.hotelRoom.createMany({ data: hotelRooms })
    await prisma.role.createMany({ data: roles })
    await prisma.user.createMany({ data: users })
    await prisma.userRole.createMany({ data: userRoles })
    await prisma.membership.createMany({ data: memberships })
    await resetMembershipSequence()
    await prisma.game.createMany({ data: games })
    await prisma.gameChoice.createMany({ data: gameChoices })
    await prisma.gameSubmission.createMany({ data: gameSubmissions })
    await prisma.gameAssignment.createMany({ data: gameAssignments })
  } catch (error) {
    console.error('Error seeding test database:', error)
    throw error
  } finally {
    await prisma.$disconnect()
  }
}
