/* eslint-disable */
import * as types from './graphql'
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
  'query getGamesBySlotForSignup($year: Int!, $slotId: Int!) {\n  games(\n    filter: {or: [{and: [{or: [{year: {equalTo: $year}}, {year: {equalTo: 0}}]}, {slotId: {equalTo: $slotId}}]}, {and: [{year: {equalTo: 0}}, {slotId: {isNull: true}}]}]}\n    orderBy: [YEAR_DESC, SLOT_ID_ASC, NAME_ASC]\n  ) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nquery getGamesBySlot($year: Int!, $slotId: Int!) {\n  games(\n    condition: {year: $year, slotId: $slotId}\n    orderBy: [SLOT_ID_ASC, NAME_ASC]\n  ) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nquery getGamesByYear($year: Int!) {\n  games(\n    filter: {or: [{and: [{or: [{year: {equalTo: $year}}, {year: {equalTo: 0}}]}]}, {and: [{year: {equalTo: 0}}]}]}\n    orderBy: [YEAR_DESC, SLOT_ID_ASC, NAME_ASC]\n  ) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n        room {\n          ...gameRoomFields\n        }\n      }\n    }\n  }\n}\n\nquery getSmallGamesByYear($year: Int!) {\n  games(condition: {year: $year}, orderBy: [SLOT_ID_ASC, NAME_ASC], first: 1) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nmutation updateGameByNodeId($input: UpdateGameByNodeIdInput!) {\n  updateGameByNodeId(input: $input) {\n    game {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nmutation updateGame($input: UpdateGameInput!) {\n  updateGame(input: $input) {\n    game {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nmutation createGame($input: CreateGameInput!) {\n  createGame(input: $input) {\n    game {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nmutation deleteGame($input: DeleteGameInput!) {\n  deleteGame(input: $input) {\n    clientMutationId\n    deletedGameNodeId\n  }\n}\n\nquery getFirstGameOfSlot($year: Int!) {\n  games(orderBy: NAME_ASC, condition: {slotId: 1, year: $year}, first: 1) {\n    nodes {\n      ...gameFields\n      gameAssignments(filter: {gm: {lessThan: 0}}) {\n        nodes {\n          nodeId\n          gm\n          member {\n            user {\n              email\n              fullName\n            }\n          }\n        }\n      }\n    }\n  }\n}\n\nquery getGamesByAuthor($id: Int!) {\n  user(id: $id) {\n    authoredGames {\n      nodes {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nquery getGamesByYearAndAuthor($year: Int!, $id: Int!) {\n  games(condition: {authorId: $id, year: $year}) {\n    nodes {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nquery getGameById($id: Int!) {\n  game(id: $id) {\n    ...gameFields\n    ...gameGms\n  }\n}': typeof types.GetGamesBySlotForSignupDocument
  'fragment gameAssignmentFields on GameAssignment {\n  gameId\n  gm\n  memberId\n  nodeId\n  year\n}': typeof types.GameAssignmentFieldsFragmentDoc
  'query getGameAssignmentsByYear($year: Int!) {\n  gameAssignments(condition: {year: $year}) {\n    nodes {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nquery getGameAssignmentsByGameId($gameId: Int!) {\n  gameAssignments(condition: {gameId: $gameId}) {\n    nodes {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nquery getGameAssignmentsByMemberId($memberId: Int!) {\n  gameAssignments(condition: {memberId: $memberId}) {\n    nodes {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nmutation updateGameAssignmentByNodeId($input: UpdateGameAssignmentByNodeIdInput!) {\n  updateGameAssignmentByNodeId(input: $input) {\n    gameAssignment {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nmutation createGameAssignment($input: CreateGameAssignmentInput!) {\n  createGameAssignment(input: $input) {\n    gameAssignment {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nmutation deleteGameAssignment($input: DeleteGameAssignmentByNodeIdInput!) {\n  deleteGameAssignmentByNodeId(input: $input) {\n    clientMutationId\n    deletedGameAssignmentNodeId\n  }\n}\n\nquery getSchedule($memberId: Int!) {\n  gameAssignments(\n    condition: {memberId: $memberId}\n    filter: {gm: {greaterThanOrEqualTo: 0}}\n  ) {\n    nodes {\n      game {\n        ...gameFields\n        gameAssignments(filter: {gm: {greaterThanOrEqualTo: 0}}) {\n          nodes {\n            ...assignmentFields\n          }\n        }\n      }\n      ...gameAssignmentFields\n    }\n  }\n}': typeof types.GetGameAssignmentsByYearDocument
  'fragment gameSubmissionFields on GameSubmission {\n  id\n  memberId\n  message\n  nodeId\n  year\n}\n\nfragment gameChoiceFields on GameChoice {\n  gameId\n  id\n  memberId\n  nodeId\n  rank\n  returningPlayer\n  slotId\n  year\n}\n\nmutation createGameChoices($year: Int!, $slots: Int!, $memberId: Int!) {\n  createBareSlotChoices(\n    input: {memberId: $memberId, yearNo: $year, noSlots: $slots}\n  ) {\n    clientMutationId\n  }\n}\n\nquery getGameChoices($year: Int!, $memberId: Int!) {\n  gameSubmissions(condition: {memberId: $memberId, year: $year}) {\n    nodes {\n      ...gameSubmissionFields\n    }\n  }\n  gameChoices(condition: {memberId: $memberId, year: $year}) {\n    nodes {\n      ...gameChoiceFields\n    }\n  }\n}\n\nquery readGameChoice($id: Int!) {\n  gameChoice(id: $id) {\n    ...gameChoiceFields\n  }\n}\n\nmutation createGameSubmission($input: CreateGameSubmissionInput!) {\n  createGameSubmission(input: $input) {\n    clientMutationId\n    gameSubmission {\n      ...gameSubmissionFields\n    }\n  }\n}\n\nmutation updateGameSubmissionByNodeId($input: UpdateGameSubmissionByNodeIdInput!) {\n  updateGameSubmissionByNodeId(input: $input) {\n    clientMutationId\n    gameSubmission {\n      ...gameSubmissionFields\n    }\n  }\n}\n\nmutation createGameChoice($input: CreateGameChoiceInput!) {\n  createGameChoice(input: $input) {\n    clientMutationId\n    gameChoice {\n      ...gameChoiceFields\n    }\n  }\n}\n\nmutation updateGameChoiceByNodeId($input: UpdateGameChoiceByNodeIdInput!) {\n  updateGameChoiceByNodeId(input: $input) {\n    clientMutationId\n    gameChoice {\n      ...gameChoiceFields\n    }\n  }\n}': typeof types.GameSubmissionFieldsFragmentDoc
  'fragment gameFields on Game {\n  nodeId\n  id\n  name\n  gmNames\n  description\n  genre\n  type\n  setting\n  charInstructions\n  playerMax\n  playerMin\n  playerPreference\n  returningPlayers\n  playersContactGm\n  gameContactEmail\n  estimatedLength\n  slotPreference\n  lateStart\n  lateFinish\n  slotConflicts\n  message\n  slotId\n  teenFriendly\n  year\n  full\n  roomId\n  room {\n    description\n  }\n}\n\nfragment assignmentFields on GameAssignment {\n  ...gameAssignmentFields\n  member {\n    user {\n      email\n      fullName\n    }\n  }\n}\n\nfragment gameGms on Game {\n  gameAssignments(filter: {gm: {lessThan: 0}}) {\n    nodes {\n      ...assignmentFields\n    }\n  }\n}': typeof types.GameFieldsFragmentDoc
  'fragment gameRoomFields on Room {\n  id\n  description\n  size\n  type\n  updated\n}\n\nquery getGameRooms {\n  rooms {\n    nodes {\n      ...gameRoomFields\n    }\n  }\n}\n\nmutation updateGameRoom($input: UpdateRoomInput!) {\n  updateRoom(input: $input) {\n    room {\n      ...gameRoomFields\n    }\n  }\n}\n\nmutation createGameRoom($input: CreateRoomInput!) {\n  createRoom(input: $input) {\n    room {\n      ...gameRoomFields\n    }\n  }\n}\n\nmutation deleteGameRoom($input: DeleteRoomInput!) {\n  deleteRoom(input: $input) {\n    clientMutationId\n    deletedRoomNodeId\n  }\n}\n\nquery getGameRoomAndGames($year: Int) {\n  rooms {\n    nodes {\n      id\n      description\n      games(condition: {year: $year}, orderBy: SLOT_ID_ASC) {\n        nodes {\n          id\n          name\n          slotId\n          gmNames\n        }\n      }\n    }\n  }\n}': typeof types.GameRoomFieldsFragmentDoc
  'query getStripe {\n  stripes {\n    nodes {\n      id\n      data\n    }\n  }\n}\n\nmutation createStripe($input: CreateStripeInput!) {\n  createStripe(input: $input) {\n    clientMutationId\n  }\n}': typeof types.GetStripeDocument
  'query getTransaction {\n  transactions {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByYear($year: Int!) {\n  transactions(condition: {year: $year}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByUser($userId: Int!) {\n  transactions(condition: {userId: $userId}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByYearAndUser($year: Int!, $userId: Int!) {\n  transactions(condition: {year: $year, userId: $userId}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByYearAndMember($year: Int!, $memberId: Int!) {\n  transactions(condition: {year: $year, memberId: $memberId}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nmutation createTransaction($input: CreateTransactionInput!) {\n  createTransaction(input: $input) {\n    transaction {\n      ...transactionFields\n    }\n  }\n}\n\nmutation deleteTransaction($input: DeleteTransactionInput!) {\n  deleteTransaction(input: $input) {\n    clientMutationId\n    deletedTransactionNodeId\n  }\n}\n\nmutation updateTransactionByNodeId($input: UpdateTransactionByNodeIdInput!) {\n  updateTransactionByNodeId(input: $input) {\n    transaction {\n      ...transactionFields\n    }\n  }\n}': typeof types.GetTransactionDocument
  'fragment transactionFields on Transaction {\n  id\n  nodeId\n  userId\n  memberId\n  amount\n  origin\n  stripe\n  timestamp\n  year\n  notes\n  data\n  user {\n    fullName\n  }\n  userByOrigin {\n    fullName\n  }\n  member {\n    year\n  }\n}': typeof types.TransactionFieldsFragmentDoc
}
const documents: Documents = {
  'query getGamesBySlotForSignup($year: Int!, $slotId: Int!) {\n  games(\n    filter: {or: [{and: [{or: [{year: {equalTo: $year}}, {year: {equalTo: 0}}]}, {slotId: {equalTo: $slotId}}]}, {and: [{year: {equalTo: 0}}, {slotId: {isNull: true}}]}]}\n    orderBy: [YEAR_DESC, SLOT_ID_ASC, NAME_ASC]\n  ) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nquery getGamesBySlot($year: Int!, $slotId: Int!) {\n  games(\n    condition: {year: $year, slotId: $slotId}\n    orderBy: [SLOT_ID_ASC, NAME_ASC]\n  ) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nquery getGamesByYear($year: Int!) {\n  games(\n    filter: {or: [{and: [{or: [{year: {equalTo: $year}}, {year: {equalTo: 0}}]}]}, {and: [{year: {equalTo: 0}}]}]}\n    orderBy: [YEAR_DESC, SLOT_ID_ASC, NAME_ASC]\n  ) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n        room {\n          ...gameRoomFields\n        }\n      }\n    }\n  }\n}\n\nquery getSmallGamesByYear($year: Int!) {\n  games(condition: {year: $year}, orderBy: [SLOT_ID_ASC, NAME_ASC], first: 1) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nmutation updateGameByNodeId($input: UpdateGameByNodeIdInput!) {\n  updateGameByNodeId(input: $input) {\n    game {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nmutation updateGame($input: UpdateGameInput!) {\n  updateGame(input: $input) {\n    game {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nmutation createGame($input: CreateGameInput!) {\n  createGame(input: $input) {\n    game {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nmutation deleteGame($input: DeleteGameInput!) {\n  deleteGame(input: $input) {\n    clientMutationId\n    deletedGameNodeId\n  }\n}\n\nquery getFirstGameOfSlot($year: Int!) {\n  games(orderBy: NAME_ASC, condition: {slotId: 1, year: $year}, first: 1) {\n    nodes {\n      ...gameFields\n      gameAssignments(filter: {gm: {lessThan: 0}}) {\n        nodes {\n          nodeId\n          gm\n          member {\n            user {\n              email\n              fullName\n            }\n          }\n        }\n      }\n    }\n  }\n}\n\nquery getGamesByAuthor($id: Int!) {\n  user(id: $id) {\n    authoredGames {\n      nodes {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nquery getGamesByYearAndAuthor($year: Int!, $id: Int!) {\n  games(condition: {authorId: $id, year: $year}) {\n    nodes {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nquery getGameById($id: Int!) {\n  game(id: $id) {\n    ...gameFields\n    ...gameGms\n  }\n}':
    types.GetGamesBySlotForSignupDocument,
  'fragment gameAssignmentFields on GameAssignment {\n  gameId\n  gm\n  memberId\n  nodeId\n  year\n}':
    types.GameAssignmentFieldsFragmentDoc,
  'query getGameAssignmentsByYear($year: Int!) {\n  gameAssignments(condition: {year: $year}) {\n    nodes {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nquery getGameAssignmentsByGameId($gameId: Int!) {\n  gameAssignments(condition: {gameId: $gameId}) {\n    nodes {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nquery getGameAssignmentsByMemberId($memberId: Int!) {\n  gameAssignments(condition: {memberId: $memberId}) {\n    nodes {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nmutation updateGameAssignmentByNodeId($input: UpdateGameAssignmentByNodeIdInput!) {\n  updateGameAssignmentByNodeId(input: $input) {\n    gameAssignment {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nmutation createGameAssignment($input: CreateGameAssignmentInput!) {\n  createGameAssignment(input: $input) {\n    gameAssignment {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nmutation deleteGameAssignment($input: DeleteGameAssignmentByNodeIdInput!) {\n  deleteGameAssignmentByNodeId(input: $input) {\n    clientMutationId\n    deletedGameAssignmentNodeId\n  }\n}\n\nquery getSchedule($memberId: Int!) {\n  gameAssignments(\n    condition: {memberId: $memberId}\n    filter: {gm: {greaterThanOrEqualTo: 0}}\n  ) {\n    nodes {\n      game {\n        ...gameFields\n        gameAssignments(filter: {gm: {greaterThanOrEqualTo: 0}}) {\n          nodes {\n            ...assignmentFields\n          }\n        }\n      }\n      ...gameAssignmentFields\n    }\n  }\n}':
    types.GetGameAssignmentsByYearDocument,
  'fragment gameSubmissionFields on GameSubmission {\n  id\n  memberId\n  message\n  nodeId\n  year\n}\n\nfragment gameChoiceFields on GameChoice {\n  gameId\n  id\n  memberId\n  nodeId\n  rank\n  returningPlayer\n  slotId\n  year\n}\n\nmutation createGameChoices($year: Int!, $slots: Int!, $memberId: Int!) {\n  createBareSlotChoices(\n    input: {memberId: $memberId, yearNo: $year, noSlots: $slots}\n  ) {\n    clientMutationId\n  }\n}\n\nquery getGameChoices($year: Int!, $memberId: Int!) {\n  gameSubmissions(condition: {memberId: $memberId, year: $year}) {\n    nodes {\n      ...gameSubmissionFields\n    }\n  }\n  gameChoices(condition: {memberId: $memberId, year: $year}) {\n    nodes {\n      ...gameChoiceFields\n    }\n  }\n}\n\nquery readGameChoice($id: Int!) {\n  gameChoice(id: $id) {\n    ...gameChoiceFields\n  }\n}\n\nmutation createGameSubmission($input: CreateGameSubmissionInput!) {\n  createGameSubmission(input: $input) {\n    clientMutationId\n    gameSubmission {\n      ...gameSubmissionFields\n    }\n  }\n}\n\nmutation updateGameSubmissionByNodeId($input: UpdateGameSubmissionByNodeIdInput!) {\n  updateGameSubmissionByNodeId(input: $input) {\n    clientMutationId\n    gameSubmission {\n      ...gameSubmissionFields\n    }\n  }\n}\n\nmutation createGameChoice($input: CreateGameChoiceInput!) {\n  createGameChoice(input: $input) {\n    clientMutationId\n    gameChoice {\n      ...gameChoiceFields\n    }\n  }\n}\n\nmutation updateGameChoiceByNodeId($input: UpdateGameChoiceByNodeIdInput!) {\n  updateGameChoiceByNodeId(input: $input) {\n    clientMutationId\n    gameChoice {\n      ...gameChoiceFields\n    }\n  }\n}':
    types.GameSubmissionFieldsFragmentDoc,
  'fragment gameFields on Game {\n  nodeId\n  id\n  name\n  gmNames\n  description\n  genre\n  type\n  setting\n  charInstructions\n  playerMax\n  playerMin\n  playerPreference\n  returningPlayers\n  playersContactGm\n  gameContactEmail\n  estimatedLength\n  slotPreference\n  lateStart\n  lateFinish\n  slotConflicts\n  message\n  slotId\n  teenFriendly\n  year\n  full\n  roomId\n  room {\n    description\n  }\n}\n\nfragment assignmentFields on GameAssignment {\n  ...gameAssignmentFields\n  member {\n    user {\n      email\n      fullName\n    }\n  }\n}\n\nfragment gameGms on Game {\n  gameAssignments(filter: {gm: {lessThan: 0}}) {\n    nodes {\n      ...assignmentFields\n    }\n  }\n}':
    types.GameFieldsFragmentDoc,
  'fragment gameRoomFields on Room {\n  id\n  description\n  size\n  type\n  updated\n}\n\nquery getGameRooms {\n  rooms {\n    nodes {\n      ...gameRoomFields\n    }\n  }\n}\n\nmutation updateGameRoom($input: UpdateRoomInput!) {\n  updateRoom(input: $input) {\n    room {\n      ...gameRoomFields\n    }\n  }\n}\n\nmutation createGameRoom($input: CreateRoomInput!) {\n  createRoom(input: $input) {\n    room {\n      ...gameRoomFields\n    }\n  }\n}\n\nmutation deleteGameRoom($input: DeleteRoomInput!) {\n  deleteRoom(input: $input) {\n    clientMutationId\n    deletedRoomNodeId\n  }\n}\n\nquery getGameRoomAndGames($year: Int) {\n  rooms {\n    nodes {\n      id\n      description\n      games(condition: {year: $year}, orderBy: SLOT_ID_ASC) {\n        nodes {\n          id\n          name\n          slotId\n          gmNames\n        }\n      }\n    }\n  }\n}':
    types.GameRoomFieldsFragmentDoc,
  'query getStripe {\n  stripes {\n    nodes {\n      id\n      data\n    }\n  }\n}\n\nmutation createStripe($input: CreateStripeInput!) {\n  createStripe(input: $input) {\n    clientMutationId\n  }\n}':
    types.GetStripeDocument,
  'query getTransaction {\n  transactions {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByYear($year: Int!) {\n  transactions(condition: {year: $year}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByUser($userId: Int!) {\n  transactions(condition: {userId: $userId}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByYearAndUser($year: Int!, $userId: Int!) {\n  transactions(condition: {year: $year, userId: $userId}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByYearAndMember($year: Int!, $memberId: Int!) {\n  transactions(condition: {year: $year, memberId: $memberId}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nmutation createTransaction($input: CreateTransactionInput!) {\n  createTransaction(input: $input) {\n    transaction {\n      ...transactionFields\n    }\n  }\n}\n\nmutation deleteTransaction($input: DeleteTransactionInput!) {\n  deleteTransaction(input: $input) {\n    clientMutationId\n    deletedTransactionNodeId\n  }\n}\n\nmutation updateTransactionByNodeId($input: UpdateTransactionByNodeIdInput!) {\n  updateTransactionByNodeId(input: $input) {\n    transaction {\n      ...transactionFields\n    }\n  }\n}':
    types.GetTransactionDocument,
  'fragment transactionFields on Transaction {\n  id\n  nodeId\n  userId\n  memberId\n  amount\n  origin\n  stripe\n  timestamp\n  year\n  notes\n  data\n  user {\n    fullName\n  }\n  userByOrigin {\n    fullName\n  }\n  member {\n    year\n  }\n}':
    types.TransactionFieldsFragmentDoc,
}

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'query getGamesBySlotForSignup($year: Int!, $slotId: Int!) {\n  games(\n    filter: {or: [{and: [{or: [{year: {equalTo: $year}}, {year: {equalTo: 0}}]}, {slotId: {equalTo: $slotId}}]}, {and: [{year: {equalTo: 0}}, {slotId: {isNull: true}}]}]}\n    orderBy: [YEAR_DESC, SLOT_ID_ASC, NAME_ASC]\n  ) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nquery getGamesBySlot($year: Int!, $slotId: Int!) {\n  games(\n    condition: {year: $year, slotId: $slotId}\n    orderBy: [SLOT_ID_ASC, NAME_ASC]\n  ) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nquery getGamesByYear($year: Int!) {\n  games(\n    filter: {or: [{and: [{or: [{year: {equalTo: $year}}, {year: {equalTo: 0}}]}]}, {and: [{year: {equalTo: 0}}]}]}\n    orderBy: [YEAR_DESC, SLOT_ID_ASC, NAME_ASC]\n  ) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n        room {\n          ...gameRoomFields\n        }\n      }\n    }\n  }\n}\n\nquery getSmallGamesByYear($year: Int!) {\n  games(condition: {year: $year}, orderBy: [SLOT_ID_ASC, NAME_ASC], first: 1) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nmutation updateGameByNodeId($input: UpdateGameByNodeIdInput!) {\n  updateGameByNodeId(input: $input) {\n    game {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nmutation updateGame($input: UpdateGameInput!) {\n  updateGame(input: $input) {\n    game {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nmutation createGame($input: CreateGameInput!) {\n  createGame(input: $input) {\n    game {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nmutation deleteGame($input: DeleteGameInput!) {\n  deleteGame(input: $input) {\n    clientMutationId\n    deletedGameNodeId\n  }\n}\n\nquery getFirstGameOfSlot($year: Int!) {\n  games(orderBy: NAME_ASC, condition: {slotId: 1, year: $year}, first: 1) {\n    nodes {\n      ...gameFields\n      gameAssignments(filter: {gm: {lessThan: 0}}) {\n        nodes {\n          nodeId\n          gm\n          member {\n            user {\n              email\n              fullName\n            }\n          }\n        }\n      }\n    }\n  }\n}\n\nquery getGamesByAuthor($id: Int!) {\n  user(id: $id) {\n    authoredGames {\n      nodes {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nquery getGamesByYearAndAuthor($year: Int!, $id: Int!) {\n  games(condition: {authorId: $id, year: $year}) {\n    nodes {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nquery getGameById($id: Int!) {\n  game(id: $id) {\n    ...gameFields\n    ...gameGms\n  }\n}',
): (typeof documents)['query getGamesBySlotForSignup($year: Int!, $slotId: Int!) {\n  games(\n    filter: {or: [{and: [{or: [{year: {equalTo: $year}}, {year: {equalTo: 0}}]}, {slotId: {equalTo: $slotId}}]}, {and: [{year: {equalTo: 0}}, {slotId: {isNull: true}}]}]}\n    orderBy: [YEAR_DESC, SLOT_ID_ASC, NAME_ASC]\n  ) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nquery getGamesBySlot($year: Int!, $slotId: Int!) {\n  games(\n    condition: {year: $year, slotId: $slotId}\n    orderBy: [SLOT_ID_ASC, NAME_ASC]\n  ) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nquery getGamesByYear($year: Int!) {\n  games(\n    filter: {or: [{and: [{or: [{year: {equalTo: $year}}, {year: {equalTo: 0}}]}]}, {and: [{year: {equalTo: 0}}]}]}\n    orderBy: [YEAR_DESC, SLOT_ID_ASC, NAME_ASC]\n  ) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n        room {\n          ...gameRoomFields\n        }\n      }\n    }\n  }\n}\n\nquery getSmallGamesByYear($year: Int!) {\n  games(condition: {year: $year}, orderBy: [SLOT_ID_ASC, NAME_ASC], first: 1) {\n    edges {\n      node {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nmutation updateGameByNodeId($input: UpdateGameByNodeIdInput!) {\n  updateGameByNodeId(input: $input) {\n    game {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nmutation updateGame($input: UpdateGameInput!) {\n  updateGame(input: $input) {\n    game {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nmutation createGame($input: CreateGameInput!) {\n  createGame(input: $input) {\n    game {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nmutation deleteGame($input: DeleteGameInput!) {\n  deleteGame(input: $input) {\n    clientMutationId\n    deletedGameNodeId\n  }\n}\n\nquery getFirstGameOfSlot($year: Int!) {\n  games(orderBy: NAME_ASC, condition: {slotId: 1, year: $year}, first: 1) {\n    nodes {\n      ...gameFields\n      gameAssignments(filter: {gm: {lessThan: 0}}) {\n        nodes {\n          nodeId\n          gm\n          member {\n            user {\n              email\n              fullName\n            }\n          }\n        }\n      }\n    }\n  }\n}\n\nquery getGamesByAuthor($id: Int!) {\n  user(id: $id) {\n    authoredGames {\n      nodes {\n        ...gameFields\n        ...gameGms\n      }\n    }\n  }\n}\n\nquery getGamesByYearAndAuthor($year: Int!, $id: Int!) {\n  games(condition: {authorId: $id, year: $year}) {\n    nodes {\n      ...gameFields\n      ...gameGms\n    }\n  }\n}\n\nquery getGameById($id: Int!) {\n  game(id: $id) {\n    ...gameFields\n    ...gameGms\n  }\n}']
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'fragment gameAssignmentFields on GameAssignment {\n  gameId\n  gm\n  memberId\n  nodeId\n  year\n}',
): (typeof documents)['fragment gameAssignmentFields on GameAssignment {\n  gameId\n  gm\n  memberId\n  nodeId\n  year\n}']
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'query getGameAssignmentsByYear($year: Int!) {\n  gameAssignments(condition: {year: $year}) {\n    nodes {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nquery getGameAssignmentsByGameId($gameId: Int!) {\n  gameAssignments(condition: {gameId: $gameId}) {\n    nodes {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nquery getGameAssignmentsByMemberId($memberId: Int!) {\n  gameAssignments(condition: {memberId: $memberId}) {\n    nodes {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nmutation updateGameAssignmentByNodeId($input: UpdateGameAssignmentByNodeIdInput!) {\n  updateGameAssignmentByNodeId(input: $input) {\n    gameAssignment {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nmutation createGameAssignment($input: CreateGameAssignmentInput!) {\n  createGameAssignment(input: $input) {\n    gameAssignment {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nmutation deleteGameAssignment($input: DeleteGameAssignmentByNodeIdInput!) {\n  deleteGameAssignmentByNodeId(input: $input) {\n    clientMutationId\n    deletedGameAssignmentNodeId\n  }\n}\n\nquery getSchedule($memberId: Int!) {\n  gameAssignments(\n    condition: {memberId: $memberId}\n    filter: {gm: {greaterThanOrEqualTo: 0}}\n  ) {\n    nodes {\n      game {\n        ...gameFields\n        gameAssignments(filter: {gm: {greaterThanOrEqualTo: 0}}) {\n          nodes {\n            ...assignmentFields\n          }\n        }\n      }\n      ...gameAssignmentFields\n    }\n  }\n}',
): (typeof documents)['query getGameAssignmentsByYear($year: Int!) {\n  gameAssignments(condition: {year: $year}) {\n    nodes {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nquery getGameAssignmentsByGameId($gameId: Int!) {\n  gameAssignments(condition: {gameId: $gameId}) {\n    nodes {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nquery getGameAssignmentsByMemberId($memberId: Int!) {\n  gameAssignments(condition: {memberId: $memberId}) {\n    nodes {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nmutation updateGameAssignmentByNodeId($input: UpdateGameAssignmentByNodeIdInput!) {\n  updateGameAssignmentByNodeId(input: $input) {\n    gameAssignment {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nmutation createGameAssignment($input: CreateGameAssignmentInput!) {\n  createGameAssignment(input: $input) {\n    gameAssignment {\n      ...gameAssignmentFields\n    }\n  }\n}\n\nmutation deleteGameAssignment($input: DeleteGameAssignmentByNodeIdInput!) {\n  deleteGameAssignmentByNodeId(input: $input) {\n    clientMutationId\n    deletedGameAssignmentNodeId\n  }\n}\n\nquery getSchedule($memberId: Int!) {\n  gameAssignments(\n    condition: {memberId: $memberId}\n    filter: {gm: {greaterThanOrEqualTo: 0}}\n  ) {\n    nodes {\n      game {\n        ...gameFields\n        gameAssignments(filter: {gm: {greaterThanOrEqualTo: 0}}) {\n          nodes {\n            ...assignmentFields\n          }\n        }\n      }\n      ...gameAssignmentFields\n    }\n  }\n}']
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'fragment gameSubmissionFields on GameSubmission {\n  id\n  memberId\n  message\n  nodeId\n  year\n}\n\nfragment gameChoiceFields on GameChoice {\n  gameId\n  id\n  memberId\n  nodeId\n  rank\n  returningPlayer\n  slotId\n  year\n}\n\nmutation createGameChoices($year: Int!, $slots: Int!, $memberId: Int!) {\n  createBareSlotChoices(\n    input: {memberId: $memberId, yearNo: $year, noSlots: $slots}\n  ) {\n    clientMutationId\n  }\n}\n\nquery getGameChoices($year: Int!, $memberId: Int!) {\n  gameSubmissions(condition: {memberId: $memberId, year: $year}) {\n    nodes {\n      ...gameSubmissionFields\n    }\n  }\n  gameChoices(condition: {memberId: $memberId, year: $year}) {\n    nodes {\n      ...gameChoiceFields\n    }\n  }\n}\n\nquery readGameChoice($id: Int!) {\n  gameChoice(id: $id) {\n    ...gameChoiceFields\n  }\n}\n\nmutation createGameSubmission($input: CreateGameSubmissionInput!) {\n  createGameSubmission(input: $input) {\n    clientMutationId\n    gameSubmission {\n      ...gameSubmissionFields\n    }\n  }\n}\n\nmutation updateGameSubmissionByNodeId($input: UpdateGameSubmissionByNodeIdInput!) {\n  updateGameSubmissionByNodeId(input: $input) {\n    clientMutationId\n    gameSubmission {\n      ...gameSubmissionFields\n    }\n  }\n}\n\nmutation createGameChoice($input: CreateGameChoiceInput!) {\n  createGameChoice(input: $input) {\n    clientMutationId\n    gameChoice {\n      ...gameChoiceFields\n    }\n  }\n}\n\nmutation updateGameChoiceByNodeId($input: UpdateGameChoiceByNodeIdInput!) {\n  updateGameChoiceByNodeId(input: $input) {\n    clientMutationId\n    gameChoice {\n      ...gameChoiceFields\n    }\n  }\n}',
): (typeof documents)['fragment gameSubmissionFields on GameSubmission {\n  id\n  memberId\n  message\n  nodeId\n  year\n}\n\nfragment gameChoiceFields on GameChoice {\n  gameId\n  id\n  memberId\n  nodeId\n  rank\n  returningPlayer\n  slotId\n  year\n}\n\nmutation createGameChoices($year: Int!, $slots: Int!, $memberId: Int!) {\n  createBareSlotChoices(\n    input: {memberId: $memberId, yearNo: $year, noSlots: $slots}\n  ) {\n    clientMutationId\n  }\n}\n\nquery getGameChoices($year: Int!, $memberId: Int!) {\n  gameSubmissions(condition: {memberId: $memberId, year: $year}) {\n    nodes {\n      ...gameSubmissionFields\n    }\n  }\n  gameChoices(condition: {memberId: $memberId, year: $year}) {\n    nodes {\n      ...gameChoiceFields\n    }\n  }\n}\n\nquery readGameChoice($id: Int!) {\n  gameChoice(id: $id) {\n    ...gameChoiceFields\n  }\n}\n\nmutation createGameSubmission($input: CreateGameSubmissionInput!) {\n  createGameSubmission(input: $input) {\n    clientMutationId\n    gameSubmission {\n      ...gameSubmissionFields\n    }\n  }\n}\n\nmutation updateGameSubmissionByNodeId($input: UpdateGameSubmissionByNodeIdInput!) {\n  updateGameSubmissionByNodeId(input: $input) {\n    clientMutationId\n    gameSubmission {\n      ...gameSubmissionFields\n    }\n  }\n}\n\nmutation createGameChoice($input: CreateGameChoiceInput!) {\n  createGameChoice(input: $input) {\n    clientMutationId\n    gameChoice {\n      ...gameChoiceFields\n    }\n  }\n}\n\nmutation updateGameChoiceByNodeId($input: UpdateGameChoiceByNodeIdInput!) {\n  updateGameChoiceByNodeId(input: $input) {\n    clientMutationId\n    gameChoice {\n      ...gameChoiceFields\n    }\n  }\n}']
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'fragment gameFields on Game {\n  nodeId\n  id\n  name\n  gmNames\n  description\n  genre\n  type\n  setting\n  charInstructions\n  playerMax\n  playerMin\n  playerPreference\n  returningPlayers\n  playersContactGm\n  gameContactEmail\n  estimatedLength\n  slotPreference\n  lateStart\n  lateFinish\n  slotConflicts\n  message\n  slotId\n  teenFriendly\n  year\n  full\n  roomId\n  room {\n    description\n  }\n}\n\nfragment assignmentFields on GameAssignment {\n  ...gameAssignmentFields\n  member {\n    user {\n      email\n      fullName\n    }\n  }\n}\n\nfragment gameGms on Game {\n  gameAssignments(filter: {gm: {lessThan: 0}}) {\n    nodes {\n      ...assignmentFields\n    }\n  }\n}',
): (typeof documents)['fragment gameFields on Game {\n  nodeId\n  id\n  name\n  gmNames\n  description\n  genre\n  type\n  setting\n  charInstructions\n  playerMax\n  playerMin\n  playerPreference\n  returningPlayers\n  playersContactGm\n  gameContactEmail\n  estimatedLength\n  slotPreference\n  lateStart\n  lateFinish\n  slotConflicts\n  message\n  slotId\n  teenFriendly\n  year\n  full\n  roomId\n  room {\n    description\n  }\n}\n\nfragment assignmentFields on GameAssignment {\n  ...gameAssignmentFields\n  member {\n    user {\n      email\n      fullName\n    }\n  }\n}\n\nfragment gameGms on Game {\n  gameAssignments(filter: {gm: {lessThan: 0}}) {\n    nodes {\n      ...assignmentFields\n    }\n  }\n}']
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'fragment gameRoomFields on Room {\n  id\n  description\n  size\n  type\n  updated\n}\n\nquery getGameRooms {\n  rooms {\n    nodes {\n      ...gameRoomFields\n    }\n  }\n}\n\nmutation updateGameRoom($input: UpdateRoomInput!) {\n  updateRoom(input: $input) {\n    room {\n      ...gameRoomFields\n    }\n  }\n}\n\nmutation createGameRoom($input: CreateRoomInput!) {\n  createRoom(input: $input) {\n    room {\n      ...gameRoomFields\n    }\n  }\n}\n\nmutation deleteGameRoom($input: DeleteRoomInput!) {\n  deleteRoom(input: $input) {\n    clientMutationId\n    deletedRoomNodeId\n  }\n}\n\nquery getGameRoomAndGames($year: Int) {\n  rooms {\n    nodes {\n      id\n      description\n      games(condition: {year: $year}, orderBy: SLOT_ID_ASC) {\n        nodes {\n          id\n          name\n          slotId\n          gmNames\n        }\n      }\n    }\n  }\n}',
): (typeof documents)['fragment gameRoomFields on Room {\n  id\n  description\n  size\n  type\n  updated\n}\n\nquery getGameRooms {\n  rooms {\n    nodes {\n      ...gameRoomFields\n    }\n  }\n}\n\nmutation updateGameRoom($input: UpdateRoomInput!) {\n  updateRoom(input: $input) {\n    room {\n      ...gameRoomFields\n    }\n  }\n}\n\nmutation createGameRoom($input: CreateRoomInput!) {\n  createRoom(input: $input) {\n    room {\n      ...gameRoomFields\n    }\n  }\n}\n\nmutation deleteGameRoom($input: DeleteRoomInput!) {\n  deleteRoom(input: $input) {\n    clientMutationId\n    deletedRoomNodeId\n  }\n}\n\nquery getGameRoomAndGames($year: Int) {\n  rooms {\n    nodes {\n      id\n      description\n      games(condition: {year: $year}, orderBy: SLOT_ID_ASC) {\n        nodes {\n          id\n          name\n          slotId\n          gmNames\n        }\n      }\n    }\n  }\n}']
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'query getStripe {\n  stripes {\n    nodes {\n      id\n      data\n    }\n  }\n}\n\nmutation createStripe($input: CreateStripeInput!) {\n  createStripe(input: $input) {\n    clientMutationId\n  }\n}',
): (typeof documents)['query getStripe {\n  stripes {\n    nodes {\n      id\n      data\n    }\n  }\n}\n\nmutation createStripe($input: CreateStripeInput!) {\n  createStripe(input: $input) {\n    clientMutationId\n  }\n}']
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'query getTransaction {\n  transactions {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByYear($year: Int!) {\n  transactions(condition: {year: $year}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByUser($userId: Int!) {\n  transactions(condition: {userId: $userId}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByYearAndUser($year: Int!, $userId: Int!) {\n  transactions(condition: {year: $year, userId: $userId}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByYearAndMember($year: Int!, $memberId: Int!) {\n  transactions(condition: {year: $year, memberId: $memberId}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nmutation createTransaction($input: CreateTransactionInput!) {\n  createTransaction(input: $input) {\n    transaction {\n      ...transactionFields\n    }\n  }\n}\n\nmutation deleteTransaction($input: DeleteTransactionInput!) {\n  deleteTransaction(input: $input) {\n    clientMutationId\n    deletedTransactionNodeId\n  }\n}\n\nmutation updateTransactionByNodeId($input: UpdateTransactionByNodeIdInput!) {\n  updateTransactionByNodeId(input: $input) {\n    transaction {\n      ...transactionFields\n    }\n  }\n}',
): (typeof documents)['query getTransaction {\n  transactions {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByYear($year: Int!) {\n  transactions(condition: {year: $year}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByUser($userId: Int!) {\n  transactions(condition: {userId: $userId}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByYearAndUser($year: Int!, $userId: Int!) {\n  transactions(condition: {year: $year, userId: $userId}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nquery getTransactionByYearAndMember($year: Int!, $memberId: Int!) {\n  transactions(condition: {year: $year, memberId: $memberId}) {\n    nodes {\n      ...transactionFields\n    }\n  }\n}\n\nmutation createTransaction($input: CreateTransactionInput!) {\n  createTransaction(input: $input) {\n    transaction {\n      ...transactionFields\n    }\n  }\n}\n\nmutation deleteTransaction($input: DeleteTransactionInput!) {\n  deleteTransaction(input: $input) {\n    clientMutationId\n    deletedTransactionNodeId\n  }\n}\n\nmutation updateTransactionByNodeId($input: UpdateTransactionByNodeIdInput!) {\n  updateTransactionByNodeId(input: $input) {\n    transaction {\n      ...transactionFields\n    }\n  }\n}']
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: 'fragment transactionFields on Transaction {\n  id\n  nodeId\n  userId\n  memberId\n  amount\n  origin\n  stripe\n  timestamp\n  year\n  notes\n  data\n  user {\n    fullName\n  }\n  userByOrigin {\n    fullName\n  }\n  member {\n    year\n  }\n}',
): (typeof documents)['fragment transactionFields on Transaction {\n  id\n  nodeId\n  userId\n  memberId\n  amount\n  origin\n  stripe\n  timestamp\n  year\n  notes\n  data\n  user {\n    fullName\n  }\n  userByOrigin {\n    fullName\n  }\n  member {\n    year\n  }\n}']

export function graphql(source: string) {
  return (documents as any)[source] ?? {}
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never
